[build]
  functions = "netlify/functions"


[[edge_functions]]
function = "createPost.js"
path = "/test"

[[edge_functions]]
function = "submitReply.js"
path = "/test"

[[edge_functions]]
function = "createPost"
path = "/test"